name: Build Static Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Generate index.html
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install beautifulsoup4

      - name: Run build.py
        run: python build.py

      - name: Upload output folder (untuk dicek hasilnya)
        uses: actions/upload-artifact@v3
        with:
          name: hasil-output
          path: output/
